### ISSUE TITLE
5 second load time

### ISSUE THREAD

**Issue by pascoej** [TAMSCompSci/tamscompsci.github.io#3]
unacceptable for static site

**Comment by AdilVirani** [comment]
pls use phone as timer

**Comment by eric-clinch** [comment]
i agree]

**Comment by kroq-gar78** [comment]
It seems to work if you reload after a few seconds.

**Comment by pascoej** [comment]
it's all about first impression tho

**Comment by andrewtian** [comment]
should put assets on cdn @pascoej

On Wed, Jul 22, 2015 at 9:01 PM, John Pascoe <notifications@github.com>
wrote:

> it's all about first impression tho
>
> On Wednesday, July 22, 2015, kroq-gar78 <notifications@github.com> wrote:
>
> > It seems to work if you reload after a few seconds.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/TAMSCompSci/tamscompsci.github.io/issues/3#issuecomment-123956830
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TAMSCompSci/tamscompsci.github.io/issues/3#issuecomment-123957107>
> .
>



-- 
Andrew Tian
